### PR TITLE
A user can see the lists along their todo items

### PR DESCRIPTION
**Pull request by anatoliikryvishyn**
Mockup
a

### CODE REVIEW

**Comment by serhiir** [comment]
Hey @anatoliikryvishyn, what is the status of the pull request? I do not see all the changes related to given user story here.

**Comment by serhiir** [comment]
@anatoliikryvishyn Please rename [test name](https://github.com/anatoliikryvishyn/TaDa/commit/2ff7312effca474017304119eff2b80926798ccd#diff-42caad29f7302db239e1b4191659d2baR15) into simply "returns all lists".

**Comment by serhiir** [comment]
@anatoliikryvishyn, move [text](https://github.com/anatoliikryvishyn/TaDa/commit/0fc5adb99a9e1d526360c82cfe66e4e9a1dd39f9#diff-b7186ba040870c69d2ae394fa317ea64R9) to locale please.

**Comment by serhiir** [comment]
I'd rewrite [options](https://github.com/anatoliikryvishyn/TaDa/commit/0fc5adb99a9e1d526360c82cfe66e4e9a1dd39f9#diff-4b3d54108259db39526680971c4ac847R5) using symbols like the following:
```ruby
assert_routing '/', { controller: :lists, action: :index }
```

**Comment by serhiir** [comment]
@anatoliikryvishyn please remove bold style for list description. The rest looks good to me (LGTM).

**Comment by serhiir** [comment]
@anatoliikryvishyn, reviewed.

**Comment by anatoliikryvishyn** [comment]
@serhiir, I made some changes, based on yours comments, so please review again, also You can test here http://localhost:3001/
I didn`t rewrite options using symbols, because it returns to us string, so then test fails
```ruby
-{"controller"=>:lists, "action"=>:index}
+{"controller"=>"lists", "action"=>"index"}
```

**Comment by serhiir** [comment]
Thanks @anatoliikryvishyn, please get familiar with [GitHub Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by serhiir** [comment]
@anatoliikryvishyn, can you please provide correct url, as `http://localhost:3001/` works only for your local environment?

**Comment by anatoliikryvishyn** [comment]
@serhiir, my bad, I updated urls.

**Pull request merged**
